# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(452, 515)
        Form.setStyleSheet("background-color: rgb(0, 0, 0)")
        self.label_result = QtWidgets.QLabel(Form)
        self.label_result.setGeometry(QtCore.QRect(10, 20, 431, 81))
        self.label_result.setStyleSheet("background-color: rgb(66, 126, 126);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_result.setObjectName("label_result")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 320, 91, 71))
        self.pushButton_2.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_0 = QtWidgets.QPushButton(Form)
        self.pushButton_0.setGeometry(QtCore.QRect(130, 410, 91, 71))
        self.pushButton_0.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_1 = QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(10, 320, 91, 71))
        self.pushButton_1.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 320, 91, 71))
        self.pushButton_3.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 220, 91, 71))
        self.pushButton_4.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(130, 220, 91, 71))
        self.pushButton_5.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(250, 220, 91, 71))
        self.pushButton_6.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 130, 91, 71))
        self.pushButton_7.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(130, 130, 91, 71))
        self.pushButton_8.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(250, 130, 91, 71))
        self.pushButton_9.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_PLUS = QtWidgets.QPushButton(Form)
        self.pushButton_PLUS.setGeometry(QtCore.QRect(360, 310, 91, 71))
        self.pushButton_PLUS.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_PLUS.setObjectName("pushButton_PLUS")
        self.pushButton_MINUS = QtWidgets.QPushButton(Form)
        self.pushButton_MINUS.setGeometry(QtCore.QRect(360, 220, 91, 71))
        self.pushButton_MINUS.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_MINUS.setObjectName("pushButton_MINUS")
        self.pushButton_RAVNO = QtWidgets.QPushButton(Form)
        self.pushButton_RAVNO.setGeometry(QtCore.QRect(360, 410, 91, 71))
        self.pushButton_RAVNO.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_RAVNO.setObjectName("pushButton_RAVNO")
        self.pushButton_DELETE = QtWidgets.QPushButton(Form)
        self.pushButton_DELETE.setGeometry(QtCore.QRect(360, 130, 91, 71))
        self.pushButton_DELETE.setStyleSheet("background-color: rgb(136, 136, 136);\n"
"color: white;\n"
"font: 75 16pt \"MS Shell Dlg 2\";")
        self.pushButton_DELETE.setObjectName("pushButton_DELETE")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        self.add_functions()


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_result.setText(_translate("Form", "0"))
        self.pushButton_2.setText(_translate("Form", "2"))
        self.pushButton_0.setText(_translate("Form", "0"))
        self.pushButton_1.setText(_translate("Form", "1"))
        self.pushButton_3.setText(_translate("Form", "3"))
        self.pushButton_4.setText(_translate("Form", "4"))
        self.pushButton_5.setText(_translate("Form", "5"))
        self.pushButton_6.setText(_translate("Form", "6"))
        self.pushButton_7.setText(_translate("Form", "7"))
        self.pushButton_8.setText(_translate("Form", "8"))
        self.pushButton_9.setText(_translate("Form", "9"))
        self.pushButton_PLUS.setText(_translate("Form", "+"))
        self.pushButton_MINUS.setText(_translate("Form", "-"))
        self.pushButton_RAVNO.setText(_translate("Form", "="))
        self.pushButton_DELETE.setText(_translate("Form", "DELETE"))

    def add_functions(self):
        self.pushButton_0.clicked.connect(lambda: self.write_number(self.pushButton_0.text()))
        self.pushButton_1.clicked.connect(lambda: self.write_number(self.pushButton_1.text()))
        self.pushButton_2.clicked.connect(lambda: self.write_number(self.pushButton_2.text()))
        self.pushButton_3.clicked.connect(lambda: self.write_number(self.pushButton_3.text()))
        self.pushButton_4.clicked.connect(lambda: self.write_number(self.pushButton_4.text()))
        self.pushButton_5.clicked.connect(lambda: self.write_number(self.pushButton_5.text()))
        self.pushButton_6.clicked.connect(lambda: self.write_number(self.pushButton_6.text()))
        self.pushButton_7.clicked.connect(lambda: self.write_number(self.pushButton_7.text()))
        self.pushButton_8.clicked.connect(lambda: self.write_number(self.pushButton_8.text()))
        self.pushButton_9.clicked.connect(lambda: self.write_number(self.pushButton_9.text()))
        self.pushButton_PLUS.clicked.connect(lambda: self.write_number(self.pushButton_PLUS.text()))
        self.pushButton_MINUS.clicked.connect(lambda: self.write_number(self.pushButton_MINUS.text()))

        self.pushButton_RAVNO.clicked.connect(self.results)
        self.pushButton_DELETE.clicked.connect(self.delete)
    def write_number(self, number):
        if self.label_result.text() == '0':
            self.label_result.setText(number)
        else:
                self.label_result.setText(self.label_result.text() + number)

        
        

    def results(self):
        res = eval(self.label_result.text())
        self.label_result.setText(str(res))
   
    def delete(self):
        self.label_result.setText('0')



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
